module ludp_dma_wrapper #(
    parameter int AXI_DATA_WIDTH = 512,
    parameter int AXI_ADDR_WIDTH = 32,
    parameter int AXI_ID_WIDTH   = 4,
    parameter int AXI_MAX_BURST_LEN = 16,
    parameter int AXIS_DATA_WIDTH = 512,
    parameter int LEN_WIDTH      = 16
)(
    input  wire        clk,
    input  wire        rst,

    input  wire [AXI_ADDR_WIDTH-1:0] wr_desc_addr,
    input  wire [LEN_WIDTH-1:0]      wr_desc_len,
    input  wire                       wr_desc_valid,
    output wire                       wr_desc_ready,

    input  wire [AXIS_DATA_WIDTH-1:0] wr_axis_tdata,
    input  wire [(AXIS_DATA_WIDTH/8)-1:0] wr_axis_tkeep,
    input  wire                       wr_axis_tvalid,
    output wire                       wr_axis_tready,
    input  wire                       wr_axis_tlast,

    input  wire [AXI_ADDR_WIDTH-1:0] rd_desc_addr,
    input  wire [LEN_WIDTH-1:0]      rd_desc_len,
    input  wire                       rd_desc_valid,
    output wire                       rd_desc_ready,

    output wire [AXIS_DATA_WIDTH-1:0] rd_axis_tdata,
    output wire [(AXIS_DATA_WIDTH/8)-1:0] rd_axis_tkeep,
    output wire                       rd_axis_tvalid,
    input  wire                       rd_axis_tready,
    output wire                       rd_axis_tlast,

    output wire [AXI_ID_WIDTH-1:0]    m_axi_awid,
    output wire [AXI_ADDR_WIDTH-1:0]  m_axi_awaddr,
    output wire [7:0]                 m_axi_awlen,
    output wire [2:0]                 m_axi_awsize,
    output wire [1:0]                 m_axi_awburst,
    output wire                       m_axi_awlock,
    output wire [3:0]                 m_axi_awcache,
    output wire [2:0]                 m_axi_awprot,
    output wire                       m_axi_awvalid,
    input  wire                       m_axi_awready,
    output wire [AXI_DATA_WIDTH-1:0]  m_axi_wdata,
    output wire [(AXI_DATA_WIDTH/8)-1:0] m_axi_wstrb,
    output wire                       m_axi_wlast,
    output wire                       m_axi_wvalid,
    input  wire                       m_axi_wready,
    input  wire [AXI_ID_WIDTH-1:0]    m_axi_bid,
    input  wire [1:0]                 m_axi_bresp,
    input  wire                       m_axi_bvalid,
    output wire                       m_axi_bready,

    output wire [AXI_ID_WIDTH-1:0]    m_axi_arid,
    output wire [AXI_ADDR_WIDTH-1:0]  m_axi_araddr,
    output wire [7:0]                 m_axi_arlen,
    output wire [2:0]                 m_axi_arsize,
    output wire [1:0]                 m_axi_arburst,
    output wire                       m_axi_arlock,
    output wire [3:0]                 m_axi_arcache,
    output wire [2:0]                 m_axi_arprot,
    output wire                       m_axi_arvalid,
    input  wire                       m_axi_arready,
    input  wire [AXI_ID_WIDTH-1:0]    m_axi_rid,
    input  wire [AXI_DATA_WIDTH-1:0]  m_axi_rdata,
    input  wire [1:0]                 m_axi_rresp,
    input  wire                       m_axi_rlast,
    input  wire                       m_axi_rvalid,
    output wire                       m_axi_rready
);

    axi_dma_wr #(
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .AXI_MAX_BURST_LEN(AXI_MAX_BURST_LEN),
        .AXIS_DATA_WIDTH(AXIS_DATA_WIDTH),
        .AXIS_KEEP_ENABLE(1),
        .AXIS_KEEP_WIDTH(AXIS_DATA_WIDTH/8),
        .AXIS_LAST_ENABLE(1),
        .AXIS_ID_ENABLE(0),
        .AXIS_DEST_ENABLE(0),
        .AXIS_USER_ENABLE(0),
        .LEN_WIDTH(LEN_WIDTH),
        .TAG_WIDTH(4),
        .ENABLE_SG(0),
        .ENABLE_UNALIGNED(0)
    ) u_axi_dma_wr (
        .clk(clk),
        .rst(rst),
        .s_axis_write_desc_addr(wr_desc_addr),
        .s_axis_write_desc_len(wr_desc_len),
        .s_axis_write_desc_tag(4'h1),
        .s_axis_write_desc_valid(wr_desc_valid),
        .s_axis_write_desc_ready(wr_desc_ready),
        .m_axis_write_desc_status_len(),
        .m_axis_write_desc_status_tag(),
        .m_axis_write_desc_status_id(),
        .m_axis_write_desc_status_dest(),
        .m_axis_write_desc_status_user(),
        .m_axis_write_desc_status_error(),
        .m_axis_write_desc_status_valid(),
        .s_axis_write_data_tdata(wr_axis_tdata),
        .s_axis_write_data_tkeep(wr_axis_tkeep),
        .s_axis_write_data_tvalid(wr_axis_tvalid),
        .s_axis_write_data_tready(wr_axis_tready),
        .s_axis_write_data_tlast(wr_axis_tlast),
        .s_axis_write_data_tid(8'h0),
        .s_axis_write_data_tdest(8'h0),
        .s_axis_write_data_tuser(1'b0),
        .m_axi_awid(m_axi_awid),
        .m_axi_awaddr(m_axi_awaddr),
        .m_axi_awlen(m_axi_awlen),
        .m_axi_awsize(m_axi_awsize),
        .m_axi_awburst(m_axi_awburst),
        .m_axi_awlock(m_axi_awlock),
        .m_axi_awcache(m_axi_awcache),
        .m_axi_awprot(m_axi_awprot),
        .m_axi_awvalid(m_axi_awvalid),
        .m_axi_awready(m_axi_awready),
        .m_axi_wdata(m_axi_wdata),
        .m_axi_wstrb(m_axi_wstrb),
        .m_axi_wlast(m_axi_wlast),
        .m_axi_wvalid(m_axi_wvalid),
        .m_axi_wready(m_axi_wready),
        .m_axi_bid(m_axi_bid),
        .m_axi_bresp(m_axi_bresp),
        .m_axi_bvalid(m_axi_bvalid),
        .m_axi_bready(m_axi_bready),
        .enable(1'b1),
        .abort(1'b0)
    );

    axi_dma_rd #(
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .AXI_MAX_BURST_LEN(AXI_MAX_BURST_LEN),
        .AXIS_DATA_WIDTH(AXIS_DATA_WIDTH),
        .AXIS_KEEP_ENABLE(1),
        .AXIS_KEEP_WIDTH(AXIS_DATA_WIDTH/8),
        .AXIS_LAST_ENABLE(1),
        .AXIS_ID_ENABLE(0),
        .AXIS_DEST_ENABLE(0),
        .AXIS_USER_ENABLE(0),
        .LEN_WIDTH(LEN_WIDTH),
        .TAG_WIDTH(4),
        .ENABLE_SG(0),
        .ENABLE_UNALIGNED(0)
    ) u_axi_dma_rd (
        .clk(clk),
        .rst(rst),
        .s_axis_read_desc_addr(rd_desc_addr),
        .s_axis_read_desc_len(rd_desc_len),
        .s_axis_read_desc_tag(4'hB),
        .s_axis_read_desc_id(8'h0),
        .s_axis_read_desc_dest(8'h0),
        .s_axis_read_desc_user(1'b0),
        .s_axis_read_desc_valid(rd_desc_valid),
        .s_axis_read_desc_ready(rd_desc_ready),
        .m_axis_read_desc_status_tag(),
        .m_axis_read_desc_status_error(),
        .m_axis_read_desc_status_valid(),
        .m_axis_read_data_tdata(rd_axis_tdata),
        .m_axis_read_data_tkeep(rd_axis_tkeep),
        .m_axis_read_data_tvalid(rd_axis_tvalid),
        .m_axis_read_data_tready(rd_axis_tready),
        .m_axis_read_data_tlast(rd_axis_tlast),
        .m_axis_read_data_tid(),
        .m_axis_read_data_tdest(),
        .m_axis_read_data_tuser(),
        .m_axi_arid(m_axi_arid),
        .m_axi_araddr(m_axi_araddr),
        .m_axi_arlen(m_axi_arlen),
        .m_axi_arsize(m_axi_arsize),
        .m_axi_arburst(m_axi_arburst),
        .m_axi_arlock(m_axi_arlock),
        .m_axi_arcache(m_axi_arcache),
        .m_axi_arprot(m_axi_arprot),
        .m_axi_arvalid(m_axi_arvalid),
        .m_axi_arready(m_axi_arready),
        .m_axi_rid(m_axi_rid),
        .m_axi_rdata(m_axi_rdata),
        .m_axi_rresp(m_axi_rresp),
        .m_axi_rlast(m_axi_rlast),
        .m_axi_rvalid(m_axi_rvalid),
        .m_axi_rready(m_axi_rready),
        .enable(1'b1)
    );

endmodule
