dpi_fifo.sv
../rtl/ludp_protocol.sv
../rtl/icmp_echo_reply.sv
../rtl/fpga_core.v
../lib/eth/rtl/eth_mac_10g_fifo.v
../lib/eth/rtl/eth_mac_10g.v
../lib/eth/rtl/axis_xgmii_rx_64.v
../lib/eth/rtl/axis_xgmii_tx_64.v
../lib/eth/rtl/eth_phy_10g.v
../lib/eth/rtl/eth_phy_10g_rx.v
../lib/eth/rtl/eth_phy_10g_rx_if.v
../lib/eth/rtl/eth_phy_10g_rx_frame_sync.v
../lib/eth/rtl/eth_phy_10g_rx_ber_mon.v
../lib/eth/rtl/eth_phy_10g_rx_watchdog.v
../lib/eth/rtl/eth_phy_10g_tx.v
../lib/eth/rtl/eth_phy_10g_tx_if.v
../lib/eth/rtl/xgmii_baser_dec_64.v
../lib/eth/rtl/xgmii_baser_enc_64.v
../lib/eth/rtl/lfsr.v
../lib/eth/rtl/eth_axis_rx.v
../lib/eth/rtl/eth_axis_tx.v
../lib/eth/rtl/udp_complete_64.v
../lib/eth/rtl/udp_checksum_gen_64.v
../lib/eth/rtl/udp_64.v
../lib/eth/rtl/udp_ip_rx_64.v
../lib/eth/rtl/udp_ip_tx_64.v
../lib/eth/rtl/ip_complete_64.v
../lib/eth/rtl/ip_64.v
../lib/eth/rtl/ip_eth_rx_64.v
../lib/eth/rtl/ip_eth_tx_64.v
../lib/eth/rtl/ip_arb_mux.v
../lib/eth/rtl/arp.v
../lib/eth/rtl/arp_cache.v
../lib/eth/rtl/arp_eth_rx.v
../lib/eth/rtl/arp_eth_tx.v
../lib/eth/rtl/eth_arb_mux.v
../lib/eth/lib/axis/rtl/arbiter.v
../lib/eth/lib/axis/rtl/priority_encoder.v
../lib/eth/lib/axis/rtl/axis_fifo.v
../lib/eth/lib/axis/rtl/axis_async_fifo.v
../lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
../lib/eth/lib/axis/rtl/sync_reset.v
tb_fpga_core_dpi.v
