../rtl/taxi_axis_if.sv
../rtl/taxi_axis_arb_mux.sv
../rtl/taxi_arbiter.sv
../rtl/taxi_penc.sv
../rtl/ludp_protocol.sv
../rtl/ludp_protocol_rx.sv
../rtl/ludp_protocol_tx.sv
../rtl/ludp_tx_dma.sv
../rtl/ludp_tx_scheduler.sv
../rtl/icmp_echo_reply.sv
../rtl/fpga_core.v
../rtl/taxi_prim/taxi_ram_1r1w_1c.sv
../rtl/lib_eth/eth_mac_10g_fifo.v
../rtl/lib_eth/eth_mac_10g.v
../rtl/lib_eth/axis_xgmii_rx_64.v
../rtl/lib_eth/axis_xgmii_tx_64.v
../rtl/lib_eth/eth_phy_10g.v
../rtl/lib_eth/eth_phy_10g_rx.v
../rtl/lib_eth/eth_phy_10g_rx_if.v
../rtl/lib_eth/eth_phy_10g_rx_frame_sync.v
../rtl/lib_eth/eth_phy_10g_rx_ber_mon.v
../rtl/lib_eth/eth_phy_10g_rx_watchdog.v
../rtl/lib_eth/eth_phy_10g_tx.v
../rtl/lib_eth/eth_phy_10g_tx_if.v
../rtl/lib_eth/xgmii_baser_dec_64.v
../rtl/lib_eth/xgmii_baser_enc_64.v
../rtl/lib_eth/lfsr.v
../rtl/lib_eth/eth_axis_rx.v
../rtl/lib_eth/eth_axis_tx.v
../rtl/lib_eth/udp_complete_64.v
../rtl/lib_eth/udp_checksum_gen_64.v
../rtl/lib_eth/udp_64.v
../rtl/lib_eth/udp_ip_rx_64.v
../rtl/lib_eth/udp_ip_tx_64.v
../rtl/lib_eth/ip_complete_64.v
../rtl/lib_eth/ip_64.v
../rtl/lib_eth/ip_eth_rx_64.v
../rtl/lib_eth/ip_eth_tx_64.v
../rtl/lib_eth/ip_arb_mux.v
../rtl/lib_eth/arp.v
../rtl/lib_eth/arp_cache.v
../rtl/lib_eth/arp_eth_rx.v
../rtl/lib_eth/arp_eth_tx.v
../rtl/lib_eth/eth_arb_mux.v
../rtl/lib_axis/arbiter.v
../rtl/lib_axis/priority_encoder.v
../rtl/lib_axis/axis_fifo.v
../rtl/lib_axis/axis_async_fifo.v
../rtl/lib_axis/axis_async_fifo_adapter.v
../rtl/lib_axis/sync_reset.v
../rtl/lib_axis/axis_arb_mux.v
tb_fpga_core.v
